name: ROS2

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]

# Based on example provided at https://github.com/ros-tooling/setup-ros

jobs:
  # build: # Docker is not supported on macOS and Windows.
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macOS-latest, windows-latest]
  #       ros_distribution:
  #         - galactic
  #   steps:
  #     - uses: ros-tooling/setup-ros@v0.2
  #       with:
  #         required-ros-distributions: ${{ matrix.ros_distribution }}
  #     - name: build and test
  #       uses: ros-tooling/action-ros-ci@v0.2
  #       with:
  #         package-name: crazyswarm
  #         target-ros2-distro: ${{ matrix.ros_distribution }}

  build_docker: # On Linux, use docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - humble
          - iron
          - jazzy

        # Define the Docker image(s) associated with each ROS distribution.
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2

          # Iron Irwini (May 2023 - Nov 2024)
          - docker_image: ubuntu:jammy
            ros_distribution: iron
            ros_version: 2

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: motion_capture_tracking
          target-ros2-distro: ${{ matrix.ros_distribution }}
